spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DATABASE_URL:localhost}:5432/${POSTGRES_DATABASE_NAME:truyenhub}
    username: ${POSTGRES_DATABASE_USERNAME:postgres}
    password: ${POSTGRES_DATABASE_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 500MB

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

file:
  upload-dir: ${UPLOAD_DIR:uploads}
  upload-path: ${UPLOAD_PATH:uploads}
  upload:
    base-path: ${UPLOAD_BASE_PATH:uploads}
